### ISSUE TITLE
Add download as a zip on folder

### ISSUE THREAD

**Issue by b01xy** [cr/mkPirateBox#2]
Maybe it would be a nice feature to add the possibility to upload a zipped file (which would contain a folder and files for exemple) and the piratebox would unzip it on the fly when uploaded ?
Would it be complex ?
Is the CPU/Memory of router as TP-Link MR3020 powerfull enough for this kind of task ?

thks for this nice work
++b

**Comment by b01xy** [comment]
switch to https://github.com/MaStr/mkPirateBox/

**Comment by Basu607** [comment]
`hi uski Jeff high stuff`
